language: php
sudo: required
dist: trusty
group: edge
php:
  - '7.1'
#  - hhvm

services:
  - mongodb

before_script:
  # install ext-mongodb:^1.2
  - pecl install -f mongodb-1.2.9

  # composer deps
  - composer self-update
  - composer install --prefer-dist
  - composer dumpautoload -o -a

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

notifications:
  email:
    - karsten.john.gerber@googlemail.com
